---

    - name: determine if python 2.7 installed
      command: stat /opt/{{app_name}}/apps/python/py2712/bin/python2.7
      register: python_stat_result 
      failed_when: "'No such file or directory' in python_stat_result.stderr"
      ignore_errors: yes
    - include: tasks/python/setup_python.yml
      when: python_stat_result.stdout == ""

    - name: determine if pip installed
      command: stat /opt/{{app_name}}/apps/python/py2712/bin/pip2.7
      register: pip_stat_result 
      failed_when: "'No such file or directory' in pip_stat_result.stderr"
      ignore_errors: yes
    - include: tasks/python/setup_pip.yml
      when: pip_stat_result.stdout == ""

    - name: is py virtualenv/pip dep setup
      command: stat /opt/{{app_name}}/apps/python/venv
      register: pyvenv_stat_result 
      failed_when: "'No such file or directory' in pyvenv_stat_result.stderr"
      ignore_errors: yes
    - include: tasks/python/setup_pip_packages.yml
      when: pyvenv_stat_result.stdout == ""

    - name: determine if erlang 17 is installed
      command: stat /opt/{{app_name}}/apps/erlang/lib/erlang/bin/erl
      register: erlang_stat_result 
      failed_when: "'No such file or directory' in erlang_stat_result.stderr"
      ignore_errors: yes
    - include: tasks/erlang/setup_erlang.yml
      when: erlang_stat_result.stdout == ""

    - name: determine if couchDB 1.6.1 is installed
      command: stat /opt/{{app_name}}/apps/couchdb/bin/couchdb
      register: couch_stat_result 
      failed_when: "'No such file or directory' in couch_stat_result.stderr"
      ignore_errors: yes
    - include: tasks/couchdb/setup_couch.yml
      when: couch_stat_result.stdout == ""

    # - name: is couchdb running?
    #   shell: sudo service couchdb status
    #   register: couch_service_result 
    #   failed_when: "'Apache CouchDB is not running' in couch_service_result.stderr"
    #   ignore_errors: yes
    # - include: tasks/couchdb/start_couchDB.yml
    #   when: couch_service_result.stdout == ""
    # - debug: var=couch_service_result.stdout_lines

