    - name: determine if erlang 17 is installed
      command: stat /opt/{{app_name}}/apps/erlang/lib/erlang/bin/erl
      register: erlang_stat_result 
      failed_when: "'No such file or directory' in erlang_stat_result.stderr"
      ignore_errors: yes
    - include: tasks/erlang/setup_erlang.yml
      when: erlang_stat_result.stdout == ""