
##  Development VM Setup
##  
## Pip packages for python 3
##
## author: Grant Steinfeld
##
## NOTE: pip now installed automatically with python3 yes

## virtualenv_command: /opt/{{app_name}}/apps/python/py361/bin/python3 -m venv
##  virtualenv if not previously setup :)
## http://stackoverflow.com/questions/42579168/ansible-create-a-virtualenv-using-the-venv-module


## DELAYED:
---

- name: "copy pip requirements script"
  copy: src="tasks/python3/{{app_name}}_pip_requirements3.txt" dest="{{company_pythondir}}/{{app_name}}_pip_requirements3.txt" mode=0755 owner="{{company_user }}"


 # install a bunch via mulberry_pip_requirements3.txt  
- pip:
    requirements: /opt/{{app_name}}/apps/python/{{app_name}}_pip_requirements3.txt
    virtualenv: /opt/{{app_name}}/apps/python/venv3
    virtualenv_command: /opt/{{app_name}}/apps/python/py369/bin/python3 -m venv
    virtualenv_site_packages: yes

- name: list pip packages 
  shell: /opt/{{app_name}}/apps/python/venv3/bin/pip list
  register: pip_list_out

- debug: var=pip_list_out.stdout_lines
  
