## {{company_camel}} Development VM Setup
##  Python3 install
## author: Grant Steinfeld
##
##

## DELAYED:
---
# - name: "install development tools"
#   shell: yum groupinstall -y "Development Tools"

# - name: "install python prerequisites"
#   yum: name={{ item }} state=latest
#   with_items:
#       - zlib-devel
#       - bzip2-devel
#       - openssl-devel
#       - ncurses-devel
#       - xz-libs
#       - httpd-devel
#       - readline-devel
#       - htop
#       - m4
# #       - let
#       - tree
#       - lsof
#       #- ackibssh-devel
#       #- wg

## {{company_camel}} Development VM Setup
##
## author: GS
##
##

# create default directory structures

- name: "make the app dir"
  file: path="/opt/{{app_name}}" state=directory owner=dev group=dev
- name: "apps/setup/python dir creation"
  file: path="/opt/{{app_name}}/apps/setup/python" state=directory owner=dev group=dev    


- name: "copy python setup script"
  copy: src=tasks/python3/install_python3.sh dest="{{company_setupdir}}/python/install_python3.sh" mode=0755 owner="{{company_user}}"

- name: "run python installation script"
  shell: "{{company_setupdir}}/python/install_python3.sh {{app_name}}"
  become: yes
  become_user: "{{dev_user}}"
