- name: Add elastic search 5.x yum repository
  yum_repository:
      name: Elasticsearch
      description: Elasticsearch repository for 5.x packages
      baseurl: https://artifacts.elastic.co/packages/5.x/yum
      gpgcheck: yes
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled: yes

- name: "install Elasticsearch"
  yum: name={{ item }} state=latest
  with_items:
    - elasticsearch

- name: Enable Elasticsearch for auto-start
  service:
     name: "{{ item }}"
     enabled: yes
  with_items:
     - elasticsearch


- name: Make sure elasticsearch is running
  systemd: state=started name=elasticsearch

- lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#cluster.name: my-application'
    line: 'cluster.name: graylog'